spring:
  application:
    name: Albion Attendance

discord:
  token: NTkwMjk4MzQ1ODI2ODExOTE4.XQgMUg.CUwmcBkSi7sBBHqp6iqEO1EBZIY
  commands:
    join: join
    show: show
    save: save
    leave: leave

