spring:
  application:
    name: Albion Bot
  datasource:
    url: jdbc:h2:file:./albion;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

discord:
  token: TODO
  commands:
    join: $join
    show: $show
    save: $save
    leave: $leave

google:
  spreadsheet:
    name: AlbionAttendance

debug: true
