spring:
  application:
    name: Albion Bot
  datasource:
    url: jdbc:h2:file:./albion;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
    ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

discord:
  token: NTkwMjk4MzQ1ODI2ODExOTE4.XQgMUg.CUwmcBkSi7sBBHqp6iqEO1EBZIY
  commands:
    join: $join
    show: $show
    save: $save
    leave: $leave

google:
  spreadsheet:
    name: AlbionAttendance

debug: true